let token=localStorage.getItem('sami_admin_token'),me=JSON.parse(localStorage.getItem('sami_admin_user')||'null');
const menu=[['dashboard','📊 داشبورد'],['categories','🧩 دسته‌بندی‌ها'],['products','📦 محصولات'],['orders','🧾 سفارش‌ها'],['customers','👥 مشتری‌ها'],['services','🛰️ سرویس‌ها'],['tickets','🎫 تیکت‌ها'],['coupons','🎟️ کد تخفیف'],['flash','⚡ فلش‌سیل'],['wheel','🎡 گردونه شانس'],['telegram','📲 تلگرام'],['settings','⚙️ تنظیمات'],['servers','🖥️ سرورها'],['wallet','💳 کیف پول'],['vip','👑 VIP'],['loyalty','💎 وفاداری'],['missions','🎯 ماموریت‌ها'],['referral','🎁 معرفی دوستان'],['notifications','🔔 اعلان‌ها'],['analytics','📈 آمار'],['audit','🛡️ لاگ‌ها'],['backup','💾 بکاپ']];
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(m,bad=false){let t=$('#toast');t.textContent=m;t.style.borderColor=bad?'#7a2d3d':'#315a76';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+token};if(opt.body&&! (opt.body instanceof FormData))opt.headers['Content-Type']='application/json';let r=await fetch(url,opt);let j={};try{j=await r.json()}catch{}if(r.status===401){logout();throw Error('نشست مدیریت منقضی شده است')}if(!r.ok)throw Error(j.error||'خطا در عملیات');return j}
async function login(){let r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('#u').value,password:$('#p').value})});let j=await r.json();if(!r.ok){$('#le').textContent='نام کاربری یا رمز اشتباه است';return}token=j.token;me=j.user;localStorage.setItem('sami_admin_token',token);localStorage.setItem('sami_admin_user',JSON.stringify(me));boot()}
function logout(){localStorage.removeItem('sami_admin_token');localStorage.removeItem('sami_admin_user');location.reload()}
function boot(){if(!token)return;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#who').textContent='👤 '+(me?.username||'admin')+' · '+(me?.role||'owner');$('#nav').innerHTML=menu.map(x=>`<button data-nav="${x[0]}" onclick="show('${x[0]}')">${x[1]}</button>`).join('');show('dashboard')}
function setView(html){$('#view').innerHTML=html}
function buttons(html){return `<div class="actions">${html}</div>`}
async function show(type){document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===type));$('#title').textContent=menu.find(x=>x[0]===type)?.[1]||type;Promise.resolve().then(()=>({dashboard:dash,categories,products,orders,customers,services,tickets,coupons,flash,wheel,telegram,settings,servers,wallet,vip,loyalty,missions,referral,notifications,analytics,audit,backup}[type]||feature)(type)).catch(e=>setView(`<div class="content"><b>خطا:</b> ${esc(e.message)}</div>`))}
async function dash(){let d=await api('/api/dashboard');setView(`<div class="cards">${[['orders','سفارش'],['pending','در انتظار'],['approved','تأییدشده'],['revenue','فروش (تومان)'],['products','محصول'],['customers','مشتری'],['tickets','تیکت باز'],['services','سرویس']].map(([k,n])=>`<div class="stat">${n}<b>${Number(d[k]||0).toLocaleString('fa-IR')}</b></div>`).join('')}</div><div class="content"><div class="section-title"><h3>مرکز کنترل</h3><span class="pill">● ONLINE</span></div><p class="muted">از منوی سمت راست هر بخش را باز کن. همه فرم‌های این نسخه مستقیماً به API متصل‌اند و بعد از ذخیره، اطلاعات دوباره از سرور خوانده می‌شود.</p></div>`)}
async function categories(){let r=await api('/api/categories');setView(`<div class="content"><div class="section-title"><h3>فعال/غیرفعال کردن دسته‌ها</h3><span class="muted">WireGuard / DNS / V2Ray</span></div>${r.map(x=>`<div class="field" style="margin:9px 0"><b>${esc(x.name)}</b><span class="pill" style="margin:0 10px">${x.active?'فعال':'خاموش'}</span><button class="${x.active?'danger':'primary'}" onclick="toggleCat('${x.id}',${!x.active})">${x.active?'خاموش کن':'فعال کن'}</button></div>`).join('')}</div>`)}
async function toggleCat(id,active){await api('/api/categories/'+id,{method:'PUT',body:JSON.stringify({active})});toast('دسته‌بندی ذخیره شد');categories()}
async function products(){let r=await api('/api/products');setView(`<div class="content"><div class="section-title"><h3>مدیریت کامل محصولات</h3><button class="primary" onclick="editProduct()">➕ محصول جدید</button></div><div class="tablewrap"><table class="table"><thead><tr><th>محصول</th><th>دسته</th><th>قیمت</th><th>مدت</th><th>حجم</th><th>موجودی</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>${r.map(x=>`<tr><td><b>${esc(x.name)}</b>${x.featured?'<br><span class="pill">⭐ ویژه</span>':''}</td><td>${esc(x.category)}</td><td>${Number(x.price).toLocaleString('fa-IR')}</td><td>${esc(x.duration)}</td><td>${esc(x.volume)}</td><td>${x.stock}</td><td>${x.active!==false?'فعال':'خاموش'}</td><td>${buttons(`<button class="secondary" onclick='editProduct(${JSON.stringify(x)})'>✏️ ویرایش</button><button class="danger" onclick="deleteProduct('${x.id}')">🗑️ حذف</button>`)}</td></tr>`).join('')}</tbody></table></div></div>`)}
function editProduct(x={}){setView(`<div class="content"><div class="section-title"><h3>${x.id?'✏️ ویرایش محصول':'➕ محصول جدید'}</h3><button class="ghost" onclick="products()">بازگشت</button></div><div class="form-grid"><div class="field"><label>نام محصول</label><input id="pn" value="${esc(x.name)}"></div><div class="field"><label>دسته</label><select id="pc"><option value="wg" ${x.category==='wg'?'selected':''}>WireGuard</option><option value="dns" ${x.category==='dns'?'selected':''}>DNS</option><option value="v2ray" ${x.category==='v2ray'?'selected':''}>V2Ray</option></select></div><div class="field"><label>قیمت تومان</label><input id="pp" type="number" value="${x.price??0}"></div><div class="field"><label>موجودی</label><input id="ps" type="number" value="${x.stock??0}"></div><div class="field"><label>مدت</label><input id="pd" value="${esc(x.duration)}" placeholder="مثلاً 30 روز"></div><div class="field"><label>حجم</label><input id="pv" value="${esc(x.volume)}" placeholder="مثلاً 100GB"></div><label class="check"><input id="pa" type="checkbox" ${x.active!==false?'checked':''}> فعال باشد</label><label class="check"><input id="pf" type="checkbox" ${x.featured?'checked':''}> ⭐ محصول ویژه</label><div class="wide"> <button class="primary" onclick="saveProduct('${x.id||''}')">💾 ذخیره محصول</button></div></div></div>`)}
async function saveProduct(id){let b={name:$('#pn').value,category:$('#pc').value,price:Number($('#pp').value),stock:Number($('#ps').value),duration:$('#pd').value,volume:$('#pv').value,active:$('#pa').checked,featured:$('#pf').checked};await api(id?'/api/products/'+id:'/api/products',{method:id?'PUT':'POST',body:JSON.stringify(b)});toast('محصول ذخیره شد');products()}
async function deleteProduct(id){if(!confirm('این محصول حذف شود؟'))return;await api('/api/products/'+id,{method:'DELETE'});toast('محصول حذف شد');products()}
async function orders(){let r=await api('/api/orders');setView(`<div class="content"><div class="section-title"><h3>سفارش‌ها و تحویل دستی</h3><span class="muted">${r.length} سفارش</span></div><div class="tablewrap"><table class="table"><thead><tr><th>ID</th><th>محصول</th><th>مشتری</th><th>مبلغ</th><th>رسید</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>${r.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.productName)}</td><td>${esc(x.customerName)}<br>${esc(x.customerContact)}</td><td>${Number(x.amount).toLocaleString('fa-IR')}</td><td>${x.receipt?`<a href="${esc(x.receipt)}" target="_blank">🧾 مشاهده</a>`:'—'}</td><td><span class="pill">${esc(x.status)}</span>${x.delivery?'<br>✅ تحویل':''}</td><td>${buttons(`<select id="st_${x.id}"><option ${x.status==='pending'?'selected':''}>pending</option><option ${x.status==='approved'?'selected':''}>approved</option><option ${x.status==='rejected'?'selected':''}>rejected</option><option ${x.status==='delivered'?'selected':''}>delivered</option></select><button class="secondary" onclick="statusOrder('${x.id}')">💾 وضعیت</button><button class="primary" onclick='delivery(${JSON.stringify(x)})'>📤 تحویل</button>`)}</td></tr>`).join('')}</tbody></table></div></div>`)}
async function statusOrder(id){await api('/api/orders/'+id+'/status',{method:'PUT',body:JSON.stringify({status:$('#st_'+id).value})});toast('وضعیت سفارش ذخیره شد');orders()}
function delivery(x){setView(`<div class="content"><div class="section-title"><h3>📤 تحویل سفارش ${esc(x.id)}</h3><button class="ghost" onclick="orders()">بازگشت</button></div><div class="form-grid"><div class="field wide"><label>لینک اشتراک</label><input id="dl" value="${esc(x.delivery?.link)}"></div><div class="field wide"><label>فایل/متن کانفیگ WireGuard</label><textarea id="dc" rows="8">${esc(x.delivery?.config)}</textarea></div><div class="field wide"><label>QR یا آدرس تصویر QR</label><textarea id="dq" rows="3">${esc(x.delivery?.qr)}</textarea></div><div class="field wide"><label>یادداشت مشتری</label><textarea id="dn" rows="4">${esc(x.delivery?.notes)}</textarea></div><div class="wide"><button class="primary" onclick="saveDelivery('${x.id}')">💾 ثبت تحویل و بستن سفارش</button></div></div></div>`)}
async function saveDelivery(id){await api('/api/orders/'+id+'/delivery',{method:'PUT',body:JSON.stringify({link:$('#dl').value,config:$('#dc').value,qr:$('#dq').value,notes:$('#dn').value})});toast('تحویل ثبت شد');orders()}
async function customers(){let r=await api('/api/customers');genericTable('مشتری‌ها',r,[['name','نام'],['contact','تماس'],['lastOrder','آخرین سفارش'],['createdAt','تاریخ']])}
async function services(){let r=await api('/api/services');genericTable('سرویس‌ها',r,[['name','نام'],['status','وضعیت'],['id','ID']])}
async function tickets(){let r=await api('/api/tickets');setView(`<div class="content"><h3>🎫 تیکت‌ها</h3>${r.map(x=>`<div class="field"><b>${esc(x.subject)}</b> · ${esc(x.status)}<p>${esc(x.message)}</p><small>${esc(x.name)} — ${esc(x.contact)}</small><br><button class="secondary" onclick="closeTicket('${x.id}')">بستن تیکت</button></div>`).join('')||'<div class="empty">تیکتی وجود ندارد.</div>'}</div>`)}
async function closeTicket(id){await api('/api/tickets/'+id,{method:'PUT',body:JSON.stringify({status:'closed'})});toast('تیکت بسته شد');tickets()}
function genericTable(title,r,cols){setView(`<div class="content"><h3>${title}</h3><div class="tablewrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${r.map(x=>`<tr>${cols.map(c=>`<td>${esc(x[c[0]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`)}
async function coupons(){let r=await api('/api/coupons');setView(`<div class="content"><div class="section-title"><h3>🎟️ کدهای تخفیف</h3><button class="primary" onclick="couponForm()">➕ کد جدید</button></div><div class="tablewrap"><table class="table"><thead><tr><th>کد</th><th>درصد</th><th>مبلغ</th><th>محدودیت</th><th>مصرف</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>${r.map(x=>`<tr><td>${esc(x.code)}</td><td>${x.percent}%</td><td>${x.amount}</td><td>${x.limit}</td><td>${x.used}</td><td>${x.active?'فعال':'خاموش'}</td><td><button class="secondary" onclick='couponForm(${JSON.stringify(x)})'>✏️ ویرایش</button></td></tr>`).join('')}</tbody></table></div></div>`)}
function couponForm(x={}){setView(`<div class="content"><h3>🎟️ ${x.id?'ویرایش':'ساخت'} کد تخفیف</h3><div class="form-grid"><div class="field"><label>کد</label><input id="cc" value="${esc(x.code)}"></div><div class="field"><label>درصد</label><input id="cp" type="number" value="${x.percent??0}"></div><div class="field"><label>مبلغ ثابت</label><input id="ca" type="number" value="${x.amount??0}"></div><div class="field"><label>سقف استفاده</label><input id="cl" type="number" value="${x.limit??0}"></div><label class="check"><input id="cactive" type="checkbox" ${x.active!==false?'checked':''}> فعال</label><div class="wide"><button class="primary" onclick="saveCoupon('${x.id||''}')">💾 ذخیره</button></div></div></div>`)}
async function saveCoupon(id){let b={code:$('#cc').value,percent:Number($('#cp').value),amount:Number($('#ca').value),limit:Number($('#cl').value),active:$('#cactive').checked};await api(id?'/api/coupons/'+id:'/api/coupons',{method:id?'PUT':'POST',body:JSON.stringify(b)});toast('کد ذخیره شد');coupons()}
async function flash(){let s=await api('/api/settings');let f=s.flashSale||{};setView(`<div class="content"><h3>⚡ فلش‌سیل</h3><div class="form-grid"><div class="field"><label>عنوان</label><input id="ft" value="${esc(f.title)}"></div><div class="field"><label>درصد تخفیف</label><input id="fp" type="number" value="${f.percent||0}"></div><div class="field wide"><label>پایان (ISO)</label><input id="fe" value="${esc(f.endsAt)}" placeholder="2026-10-01T23:59:00"></div><label class="check"><input id="fa" type="checkbox" ${f.active?'checked':''}> فعال</label><div class="wide"><button class="primary" onclick="saveFlash()">💾 ذخیره فلش‌سیل</button></div></div></div>`)}
async function saveFlash(){let s=await api('/api/settings');s.flashSale={active:$('#fa').checked,title:$('#ft').value,percent:Number($('#fp').value),endsAt:$('#fe').value};await api('/api/settings',{method:'PUT',body:JSON.stringify({flashSale:s.flashSale})});toast('فلش‌سیل ذخیره شد')}
async function wheel(){let r=await api('/api/wheel/prizes');let s=await api('/api/settings');setView(`<div class="content"><div class="section-title"><h3>🎡 گردونه شانس</h3><button class="primary" onclick="prizeForm()">➕ جایزه</button></div><p class="muted">مجموع احتمال‌ها برای چرخش باید دقیقاً 100٪ باشد. موجودی صفر یعنی جایزه قابل برد نیست.</p><div class="tablewrap"><table class="table"><thead><tr><th>جایزه</th><th>نوع</th><th>مقدار</th><th>احتمال</th><th>موجودی</th><th>فعال</th><th>عملیات</th></tr></thead><tbody>${r.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.type)}</td><td>${esc(x.value)}</td><td>${x.probability}%</td><td>${x.inventory}</td><td>${x.active?'بله':'خیر'}</td><td><button class="secondary" onclick='prizeForm(${JSON.stringify(x)})'>✏️</button><button class="danger" onclick="deletePrize('${x.id}')">🗑️</button></td></tr>`).join('')}</tbody></table></div><div class="field"><label>گردونه فعال</label><input id="wa" type="checkbox" ${s.wheel?.active?'checked':''} style="width:auto"><button class="primary" onclick="saveWheelActive()">💾 ذخیره وضعیت</button></div></div>`)}
function prizeForm(x={}){setView(`<div class="content"><h3>🎁 ${x.id?'ویرایش':'افزودن'} جایزه</h3><div class="form-grid"><div class="field"><label>نام</label><input id="zn" value="${esc(x.name)}"></div><div class="field"><label>نوع</label><select id="zt">${['none','discount','wallet','free_days','volume','product','custom'].map(v=>`<option ${x.type===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>مقدار</label><input id="zv" value="${esc(x.value)}"></div><div class="field"><label>احتمال درصد</label><input id="zp" type="number" step="0.01" value="${x.probability??0}"></div><div class="field"><label>موجودی</label><input id="zi" type="number" value="${x.inventory??0}"></div><label class="check"><input id="za" type="checkbox" ${x.active!==false?'checked':''}> فعال</label><div class="wide"><button class="primary" onclick="savePrize('${x.id||''}')">💾 ذخیره جایزه</button></div></div></div>`)}
async function savePrize(id){let b={name:$('#zn').value,type:$('#zt').value,value:$('#zv').value,probability:Number($('#zp').value),inventory:Number($('#zi').value),active:$('#za').checked};await api(id?'/api/wheel/prizes/'+id:'/api/wheel/prizes',{method:id?'PUT':'POST',body:JSON.stringify(b)});toast('جایزه ذخیره شد');wheel()}
async function deletePrize(id){if(!confirm('جایزه حذف شود؟'))return;await api('/api/wheel/prizes/'+id,{method:'DELETE'});wheel()}
async function saveWheelActive(){let s=await api('/api/settings');s.wheel={...(s.wheel||{}),active:$('#wa').checked};await api('/api/settings',{method:'PUT',body:JSON.stringify({wheel:s.wheel})});toast('وضعیت گردونه ذخیره شد')}
async function telegram(){let s=await api('/api/settings');setView(`<div class="content"><h3>📲 اطلاعات تلگرام</h3><div class="form-grid"><div class="field"><label>Username پشتیبانی</label><input id="ts" value="${esc(s.supportUsername)}"><small>t.me/${esc(s.supportUsername)}</small></div><div class="field"><label>Username بات</label><input id="tb" value="${esc(s.botUsername)}"><small>t.me/${esc(s.botUsername)}</small></div><div class="field"><label>Username کانال</label><input id="tc" value="${esc(s.channelUsername)}"><small>t.me/${esc(s.channelUsername)}</small></div><div class="field wide"><label>Bot Token (اختیاری و خصوصی)</label><input id="tt" type="password" placeholder="برای حفظ امنیت خالی بگذارید"></div><div class="wide"><button class="primary" onclick="saveTelegram()">💾 ذخیره اطلاعات تلگرام</button></div></div></div>`)}
async function saveTelegram(){await api('/api/settings',{method:'PUT',body:JSON.stringify({supportUsername:$('#ts').value.replace('@',''),botUsername:$('#tb').value.replace('@',''),channelUsername:$('#tc').value.replace('@',''),botToken:$('#tt').value})});toast('اطلاعات تلگرام ذخیره شد')}
async function settings(){let s=await api('/api/settings');setView(`<div class="content"><h3>⚙️ تنظیمات اصلی</h3><div class="form-grid"><div class="field"><label>نام سایت</label><input id="ss" value="${esc(s.siteName)}"></div><div class="field"><label>شماره کارت</label><input id="sc" value="${esc(s.cardNumber)}"></div><div class="field"><label>نام صاحب کارت</label><input id="sn" value="${esc(s.cardName)}"></div><div class="field"><label>پشتیبانی</label><input id="sp" value="${esc(s.supportUsername)}"></div><div class="field"><label>بات</label><input id="sb" value="${esc(s.botUsername)}"></div><div class="field"><label>کانال</label><input id="sch" value="${esc(s.channelUsername)}"></div><div class="wide"><button class="primary" onclick="saveMainSettings()">💾 ذخیره همه تنظیمات</button></div></div></div>`)}
async function saveMainSettings(){await api('/api/settings',{method:'PUT',body:JSON.stringify({siteName:$('#ss').value,cardNumber:$('#sc').value,cardName:$('#sn').value,supportUsername:$('#sp').value.replace('@',''),botUsername:$('#sb').value.replace('@',''),channelUsername:$('#sch').value.replace('@','')})});toast('تنظیمات ذخیره شد')}
async function servers(){let r=await api('/api/servers');setView(`<div class="content"><div class="section-title"><h3>🖥️ سرورها</h3><button class="primary" onclick="serverForm()">➕ سرور</button></div>${r.map(x=>`<div class="field"><b>${esc(x.name)}</b> · ${esc(x.status)} · ${esc(x.host)}<br><small>Ping: ${esc(x.ping)} · Uptime: ${esc(x.uptime)} · Capacity: ${esc(x.capacity)}</small><br><button class="secondary" onclick='serverForm(${JSON.stringify(x)})'>✏️ ویرایش</button></div>`).join('')||'<div class="empty">سروری ثبت نشده.</div>'}</div>`)}
function serverForm(x={}){setView(`<div class="content"><h3>🖥️ ${x.id?'ویرایش':'افزودن'} سرور</h3><div class="form-grid"><div class="field"><label>نام</label><input id="rvn" value="${esc(x.name)}"></div><div class="field"><label>Host</label><input id="rvh" value="${esc(x.host)}"></div><div class="field"><label>وضعیت</label><select id="rvs"><option ${x.status==='online'?'selected':''}>online</option><option ${x.status==='maintenance'?'selected':''}>maintenance</option><option ${x.status==='offline'?'selected':''}>offline</option></select></div><div class="field"><label>ظرفیت</label><input id="rvc" type="number" value="${x.capacity||0}"></div><div class="field"><label>Ping</label><input id="rvp" value="${esc(x.ping)}"></div><div class="field"><label>Uptime</label><input id="rvu" value="${esc(x.uptime)}"></div><div class="wide"><button class="primary" onclick="saveServer('${x.id||''}')">💾 ذخیره</button></div></div></div>`)}
async function saveServer(id){let b={name:$('#rvn').value,host:$('#rvh').value,status:$('#rvs').value,capacity:Number($('#rvc').value),ping:$('#rvp').value,uptime:$('#rvu').value};await api(id?'/api/servers/'+id:'/api/servers',{method:id?'PUT':'POST',body:JSON.stringify(b)});toast('سرور ذخیره شد');servers()}
async function notifications(){let r=await api('/api/notifications');setView(`<div class="content"><div class="section-title"><h3>🔔 اعلان‌ها</h3><button class="primary" onclick="notificationForm()">➕ اعلان</button></div>${r.map(x=>`<div class="field"><b>${esc(x.title)}</b><p>${esc(x.message)}</p><small>${esc(x.createdAt)}</small></div>`).join('')||'<div class="empty">اعلانی نیست.</div>'}</div>`)}
function notificationForm(){setView(`<div class="content"><h3>🔔 اعلان جدید</h3><div class="field"><label>عنوان</label><input id="nt"></div><div class="field"><label>پیام</label><textarea id="nm" rows="5"></textarea></div><button class="primary" onclick="saveNotification()">ارسال اعلان</button></div>`)}
async function saveNotification(){await api('/api/notifications',{method:'POST',body:JSON.stringify({title:$('#nt').value,message:$('#nm').value})});toast('اعلان ثبت شد');notifications()}
async function analytics(){let r=await api('/api/analytics');setView(`<div class="cards"><div class="stat">فروش کل<b>${Number(r.total||0).toLocaleString('fa-IR')}</b></div><div class="stat">تعداد فروش<b>${r.orders}</b></div><div class="stat">میانگین خرید<b>${Number(r.average||0).toLocaleString('fa-IR')}</b></div></div><div class="content"><h3>فروش روزانه</h3>${Object.entries(r.daily||{}).map(([d,v])=>`<div class="field">${d} <b>${Number(v).toLocaleString('fa-IR')} تومان</b></div>`).join('')||'<div class="empty">داده‌ای نیست.</div>'}</div>`)}
async function audit(){let r=await api('/api/audit');genericTable('🛡️ لاگ عملیات',r,[['at','زمان'],['user','کاربر'],['action','عملیات'],['detail','جزئیات']])}
async function backup(){setView(`<div class="content"><h3>💾 بکاپ</h3><p class="muted">دانلود نسخه فعلی دیتابیس فروشگاه.</p><a class="primary" style="display:inline-block;text-decoration:none" href="/api/backup" onclick="return authDownload(event)">⬇️ دانلود بکاپ JSON</a></div>`)}
async function authDownload(e){e.preventDefault();let r=await fetch('/api/backup',{headers:{Authorization:'Bearer '+token}});if(!r.ok){toast('دانلود بکاپ ناموفق بود',true);return false}let b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='sami-wireguard-backup.json';a.click();URL.revokeObjectURL(a.href);return false}
async function feature(type){let r=await api('/api/feature-data?type='+encodeURIComponent(type));let items=r.items||[];setView(`<div class="content"><div class="section-title"><h3>${menu.find(x=>x[0]===type)?.[1]||type}</h3><button class="primary" onclick="featureForm('${type}')">➕ رکورد جدید</button></div><p class="muted">این بخش‌ها به‌صورت رکوردی قابل ویرایش‌اند؛ تغییرات مستقیماً در دیتابیس ذخیره می‌شود.</p><div class="tablewrap"><table class="table"><thead><tr><th>ID</th><th>اطلاعات</th><th>عملیات</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.id)}</td><td><pre style="white-space:pre-wrap;color:#cbd9e7">${esc(JSON.stringify(x,null,2))}</pre></td><td>${buttons(`<button class="secondary" onclick='featureForm(${JSON.stringify(type)},${JSON.stringify(x)})'>✏️ ویرایش</button><button class="danger" onclick="deleteFeature('${type}','${esc(x.id)}')">🗑️ حذف</button>`)}</td></tr>`).join('')||'<tr><td colspan=3><div class="empty">رکوردی وجود ندارد.</div></td></tr>'}</tbody></table></div></div>`)}
function featureForm(type,x={}){let raw=JSON.stringify(x||{},null,2);setView(`<div class="content"><div class="section-title"><h3>✏️ ویرایش ${esc(type)}</h3><button class="ghost" onclick="feature('${esc(type)}')">بازگشت</button></div><div class="field"><label>داده رکورد (JSON)</label><textarea id="featureJson" rows=18>${esc(raw)}</textarea></div><button class="primary" onclick="saveFeature('${esc(type)}','${esc(x.id||'')}')">💾 ذخیره رکورد</button></div>`)}
async function saveFeature(type,id){let b;try{b=JSON.parse($('#featureJson').value)}catch(e){toast('JSON نامعتبر است',true);return}await api(id?'/api/feature-data/'+encodeURIComponent(type)+'/'+encodeURIComponent(id):'/api/feature-data/'+encodeURIComponent(type),{method:id?'PUT':'POST',body:JSON.stringify(b)});toast('رکورد ذخیره شد');feature(type)}
async function deleteFeature(type,id){if(!confirm('این رکورد حذف شود؟'))return;await api('/api/feature-data/'+encodeURIComponent(type)+'/'+encodeURIComponent(id),{method:'DELETE'});toast('رکورد حذف شد');feature(type)}
if(token)boot();
