let T=localStorage.getItem("sami_admin");
const $=id=>document.getElementById(id);
async function api(u,o={}){o.headers={...(o.headers||{}),...(T?{Authorization:"Bearer "+T}:{})};let r=await fetch(u,o),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"خطا");return j}
async function login(){try{let d=await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:$("u").value,password:$("p").value})});T=d.token;localStorage.setItem("sami_admin",T);boot()}catch(e){$("lm").textContent=e.message}}
function logout(){localStorage.removeItem("sami_admin");location.reload()}
async function boot(){if(!T)return;$("login").classList.add("hidden");$("app").classList.remove("hidden");await load()}
async function load(){let [s,a]=await Promise.all([api("/api/admin/dashboard"),api("/api/admin/all")]);$("stats").innerHTML=Object.entries(s).map(([k,v])=>`<div class="stat"><small>${k}</small><b>${typeof v==="number"?v.toLocaleString():v}</b></div>`).join("");
for(const [id,val] of Object.entries({botId:a.settings.botId,ownerId:a.settings.ownerId,supportId:a.settings.supportId,channelId:a.settings.channelId,telegramEnabled:String(a.settings.telegramEnabled!==false),siteName:a.settings.siteName,siteNameEn:a.settings.siteNameEn,cardBank:a.settings.cardBank||"",cardNumber:a.settings.cardNumber||"",cardName:a.settings.cardName||"",currency:a.settings.currency||"تومان",paymentInstructions:a.settings.paymentInstructions||"",gatewayEnabled:String(!!a.settings.gatewayEnabled),gatewayUrl:a.settings.gatewayUrl||""}))if($(id))$(id).value=val;
$("wheel").textContent=JSON.stringify(a.wheel,null,2);let ps=a.wheel.prizes||[];["w1","w2","w3","w4"].forEach((id,i)=>{if($(id))$(id).value=ps[i]?.weight||0});renderOrders(a.orders);renderProducts(a.products,a.settings.currency)}
function renderOrders(os){let pending=os.filter(o=>["pending","approved"].includes(o.status));$("orders").innerHTML=pending.length?pending.map(o=>`<div class="order"><b>${o.productName}</b><p>Order: ${o.id}<br>Telegram ID: <strong>${o.telegramId}</strong><br>تعداد: ${o.quantity||1}<br>نام سرویس‌ها: ${(o.customNames||[]).join("، ")}<br>مبلغ: ${o.total}<br>روش: ${o.paymentMethod}<br>${o.receipt?`<a href="${o.receipt}" target="_blank">مشاهده رسید</a>`:"رسید ندارد"}</p>${o.status==="pending"?`<button onclick="approve('${o.id}')">تأیید پرداخت</button><button class="danger" onclick="rejectOrder('${o.id}')">رد پرداخت</button>`:""}<button onclick="selectDelivery('${o.id}')">تحویل</button></div>`).join(""):"سفارشی در انتظار بررسی نیست."}
function renderProducts(ps,c){$("products").innerHTML=ps.map(p=>`<div class="product"><b>${p.name}</b> — ${p.price} ${c||""} — موجودی ${p.stock} — ${p.active?"فعال":"غیرفعال"}</div>`).join("")||"محصولی نیست."}
async function approve(id){try{await api("/api/admin/orders/"+id+"/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"approved"})});await load()}catch(e){alert(e.message)}}
async function rejectOrder(id){try{await api("/api/admin/orders/"+id+"/status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"rejected"})});await load()}catch(e){alert(e.message)}}
function selectDelivery(id){$("did").value=id;window.scrollTo({top:document.querySelector("#did").closest(".card").offsetTop-80,behavior:"smooth"})}
async function deliver(){try{let fd=new FormData();fd.append("link",$("dlink").value);fd.append("serviceName",$("dservice").value);fd.append("notes",$("dnotes").value);if($("dconf").files[0])fd.append("config",$("dconf").files[0]);await api("/api/admin/orders/"+encodeURIComponent($("did").value)+"/delivery",{method:"POST",body:fd});$("dm").textContent="تحویل انجام شد.";await load()}catch(e){$("dm").textContent=e.message}}
async function searchUsers(){try{let q=$("uq").value.trim();let a=await api("/api/admin/users/search?q="+encodeURIComponent(q));$("users").innerHTML=a.length?a.map(u=>`<div class="user"><b>${u.name}</b><p>Telegram ID: <strong>${u.telegramId}</strong> · ${u.username?"@"+u.username:"بدون username"}</p><button onclick="user('${u.id}')">مشاهده کامل</button></div>`).join(""):"کاربری پیدا نشد."}catch(e){$("users").textContent=e.message}}
async function user(id){let d=await api("/api/admin/users/"+id);$("userDetails").innerHTML=`<div class="user"><h3>${d.user.name}</h3><p>Telegram ID: ${d.user.telegramId}</p><p>امتیاز: ${d.user.points}</p><h4>سفارش‌ها (${d.orders.length})</h4>${d.orders.map(o=>`<div>${o.id} — ${o.productName} — ${o.quantity||1} — ${o.status}</div>`).join("")}</div>`}
async function saveSettings(){try{let body={botId:$("botId").value,ownerId:$("ownerId").value,supportId:$("supportId").value,channelId:$("channelId").value,telegramEnabled:$("telegramEnabled").value==="true",siteName:$("siteName").value,siteNameEn:$("siteNameEn").value,cardBank:$("cardBank").value,cardNumber:$("cardNumber").value,cardName:$("cardName").value,currency:$("currency").value,paymentInstructions:$("paymentInstructions").value,gatewayEnabled:$("gatewayEnabled").value==="true",gatewayUrl:$("gatewayUrl").value};if($("botToken").value.trim())body.botToken=$("botToken").value.trim();if($("adminBotToken").value.trim())body.adminBotToken=$("adminBotToken").value.trim();await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});$("sm").textContent="تنظیمات ذخیره شد."}catch(e){$("sm").textContent=e.message}}
async function saveProduct(){try{await api("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("pn").value,nameEn:$("pne").value,price:Number($("pp").value),duration:$("pd").value,volume:$("pv").value,server:$("ps").value,stock:Number($("pst").value),category:$("pc").value,description:$("pdesc").value,active:true})});$("pn").value="";await load()}catch(e){alert(e.message)}}
async function saveCoupon(){try{await api("/api/admin/coupons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:$("ccode").value,value:Number($("cvalue").value),maxUses:Number($("cmax").value),type:"percent",active:true})});$("promoMsg").textContent="کوپن ساخته شد."}catch(e){$("promoMsg").textContent=e.message}}
async function saveFlash(){try{await api("/api/admin/flash-sale",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:true,percent:Number($("fpercent").value)})});$("promoMsg").textContent="Flash Sale فعال شد."}catch(e){$("promoMsg").textContent=e.message}}
async function saveWheel(){try{let a=await api("/api/admin/all"),p=a.wheel.prizes||[];let weights=[Number($("w1").value),Number($("w2").value),Number($("w3").value),Number($("w4").value)];if(weights.reduce((x,y)=>x+y,0)!==100)return $("wheelMsg").textContent="مجموع درصدها باید دقیقاً ۱۰۰٪ باشد.";p=p.slice(0,4);p.forEach((x,i)=>x.weight=weights[i]);await api("/api/admin/wheel",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:true,prizes:p})});$("wheelMsg").textContent="درصدها ذخیره شد.";await load()}catch(e){$("wheelMsg").textContent=e.message}}
function backup(){api("/api/admin/backup").then(d=>{const a=document.createElement('a');a.href='data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(d));a.download='sami-backup.json';a.click()}).catch(e=>alert(e.message))}
boot();
