const $=id=>document.getElementById(id);
const state={products:[],categories:[],settings:{},selected:null};
const token=()=>localStorage.getItem("sami_token");
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token()?{Authorization:"Bearer "+token()}: {})};const r=await fetch(url,opt);const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"خطا");return j}
async function init(){const d=await api("/api/store");Object.assign(state,{products:d.products,categories:d.categories,settings:d.settings});$("supportLink").href="https://t.me/"+String(d.settings.supportId).replace(/^@/,"");$("loginBtn").onclick=()=>location.href="/dashboard";renderCats();render();if(token())$("loginBtn").textContent="داشبورد"}
function renderCats(){const all=[{id:"all",name:"همه"},...state.categories];$("cats").innerHTML=all.map((c,i)=>`<button class="chip ${i===0?"active":""}" onclick="filterCat('${c.id}',this)">${c.name}</button>`).join("")}
function filterCat(c,el){document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));el.classList.add("active");render(c)}
function render(c="all"){const ps=c==="all"?state.products:state.products.filter(x=>x.category===c);$("products").innerHTML=ps.length?ps.map(p=>`<article class="product"><div class="meta">${p.protocol||"WireGuard"} · ${p.duration||""} · ${p.volume||""}</div><h3>${p.name}</h3><p>${p.description||"سرویس پایدار و آماده تحویل"}</p><div class="meta">سرور: ${p.server||"—"} · پینگ: ${p.ping||"—"} · موجودی: ${p.stock}</div><div class="price">${Number(p.price).toLocaleString("fa-IR")} ${state.settings.currency||"تومان"}</div><button class="primary buy" onclick="checkout('${p.id}')">خرید</button></article>`).join(""):"<p>محصولی موجود نیست.</p>"}
function setLang(l){localStorage.setItem("sami_lang",l);document.documentElement.lang=l;document.documentElement.dir=l==="fa"?"rtl":"ltr";document.querySelector("#langBtn").textContent=l==="fa"?"EN":"FA";if(l==="en"){document.querySelector("h1").innerHTML="Fast, stable and secure <span>Sami WireGuard</span>";document.querySelector("#plans").querySelector("h2").textContent="Choose your plan";document.querySelector("#steps").querySelector("h2").textContent="Simple purchase";document.querySelector("#faq").querySelector("h2").textContent="FAQ"}else{document.querySelector("h1").innerHTML="اتصال سریع، پایدار و امن با <span>Sami WireGuard</span>";document.querySelector("#plans").querySelector("h2").textContent="پلن مناسب خودت را انتخاب کن";document.querySelector("#steps").querySelector("h2").textContent="خرید ساده";document.querySelector("#faq").querySelector("h2").textContent="سوالات متداول"}}
function openAuth(){$("authModal").classList.remove("hidden")}function closeAuth(){$("authModal").classList.add("hidden")}
async function telegramLogin(){try{const telegramId=$("tgId").value.trim();const d=await api("/api/auth/telegram",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegramId,name:$("tgName").value,username:$("tgUsername").value})});localStorage.setItem("sami_token",d.token);closeAuth();location.href="/dashboard"}catch(e){$("authMsg").textContent=e.message}}
function checkout(id){if(!token()){openAuth();return}state.selected=state.products.find(x=>x.id===id);$("checkoutInfo").innerHTML=`<b>${state.selected.name}</b><p>${Number(state.selected.price).toLocaleString("fa-IR")} ${state.settings.currency||"تومان"}</p><p class="muted">شماره کارت: ${state.settings.cardNumber||"در پنل مدیریت تنظیم نشده"}<br>به نام: ${state.settings.cardName||"—"}</p>`;$("checkoutModal").classList.remove("hidden")}
function closeCheckout(){$("checkoutModal").classList.add("hidden")}
async function submitOrder(){try{const fd=new FormData();fd.append("productId",state.selected.id);fd.append("coupon",$("coupon").value);fd.append("referral",$("referral").value);if($("receipt").files[0])fd.append("receipt",$("receipt").files[0]);const d=await api("/api/orders",{method:"POST",body:fd});$("orderMsg").textContent=`سفارش ${d.order.id} ثبت شد و در انتظار بررسی است.`}catch(e){$("orderMsg").textContent=e.message}}
function closeCheckoutOnEsc(e){if(e.key==="Escape"){closeAuth();closeCheckout()}}document.addEventListener("keydown",closeCheckoutOnEsc);
init().then(()=>{const l=localStorage.getItem("sami_lang")||"fa";$("langBtn").onclick=()=>setLang(l==="fa"?"en":"fa");setLang(l)}).catch(console.error);
