const express=require('express');const path=require('path');const fs=require('fs');const crypto=require('crypto');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const multer=require('multer');
const app=express();const PORT=process.env.PORT||10000;const HOST=process.env.HOST||'0.0.0.0';
const ROOT=__dirname,DATA=path.join(ROOT,'data'),UPLOAD=path.join(ROOT,'uploads'),DB=path.join(DATA,'store.json');fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(UPLOAD,{recursive:true});
const id=()=>crypto.randomBytes(5).toString('hex');
const defaults={settings:{siteName:process.env.SITE_NAME||'Sami WireGuard',support:'@saman_s87',bot:'@sami91928bot',channel:'@SamiWireGuard',cardNumber:'',cardName:'',currency:'تومان',announcement:'سرویس‌های حرفه‌ای WireGuard برای گیم و استفاده روزمره',maintenance:false},products:[{id:id(),name:'WireGuard 10GB',slug:'wg-10gb',volume:'10GB',duration:'30 روز',price:120000,oldPrice:150000,server:'Germany • Premium',badge:'پرفروش',active:true,stock:12,description:'سرویس WireGuard پرسرعت مناسب Gaming و استفاده روزمره.'},{id:id(),name:'WireGuard 25GB',slug:'wg-25gb',volume:'25GB',duration:'30 روز',price:220000,oldPrice:260000,server:'Netherlands • Premium',badge:'ویژه',active:true,stock:8,description:'حجم بیشتر برای استفاده سنگین و چند دستگاه.'},{id:id(),name:'WireGuard 50GB',slug:'wg-50gb',volume:'50GB',duration:'60 روز',price:390000,oldPrice:450000,server:'Finland • Ultra',badge:'Ultra',active:true,stock:5,description:'پلن طولانی‌تر با حجم بالا.'}],orders:[],customers:[],services:[],tickets:[],coupons:[],notifications:[],audit:[]};
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(defaults,null,2));
const read=()=>JSON.parse(fs.readFileSync(DB,'utf8'));const write=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
const upload=multer({dest:UPLOAD,limits:{fileSize:10*1024*1024}});app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));const FRONTEND=['index.html','style.css','app.js','admin.html','admin.css','admin.js'];
FRONTEND.forEach(file=>app.get('/'+file,(req,res)=>res.sendFile(path.join(ROOT,file))));
app.get('/',(req,res)=>res.sendFile(path.join(ROOT,'index.html')));
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET||'dev-secret-change');next()}catch(e){res.status(401).json({error:'Unauthorized'})}}
function admin(req,res,next){auth(req,res,()=>req.user.role==='admin'?next():res.status(403).json({error:'Forbidden'}))}
function saveAudit(action,meta={}){const d=read();d.audit.unshift({id:id(),action,meta,at:new Date().toISOString()});d.audit=d.audit.slice(0,500);write(d)}
app.get('/api/health',(q,r)=>r.json({ok:true,site:'Sami WireGuard'}));
app.post('/api/login',(req,res)=>{const {username,password}=req.body;if(username===(process.env.ADMIN_USER||'admin')&&password===(process.env.ADMIN_PASSWORD||'ChangeThisNow123!')){const token=jwt.sign({role:'admin',username},process.env.JWT_SECRET||'dev-secret-change',{expiresIn:'7d'});saveAudit('admin_login',{username});return res.json({token,role:'admin'})}res.status(401).json({error:'نام کاربری یا رمز عبور اشتباه است'})});
app.get('/api/store',(req,res)=>{const d=read();res.json({settings:d.settings,products:d.products.filter(x=>x.active)});});
app.get('/api/products',admin,(req,res)=>res.json(read().products));
app.post('/api/products',admin,(req,res)=>{const d=read(),p={id:id(),...req.body,price:Number(req.body.price||0),oldPrice:Number(req.body.oldPrice||0),stock:Number(req.body.stock||0),active:req.body.active!==false};d.products.push(p);write(d);saveAudit('product_created',{id:p.id,name:p.name});res.json(p)});
app.put('/api/products/:id',admin,(req,res)=>{const d=read(),i=d.products.findIndex(x=>x.id===req.params.id);if(i<0)return res.sendStatus(404);d.products[i]={...d.products[i],...req.body,price:Number(req.body.price??d.products[i].price),oldPrice:Number(req.body.oldPrice??d.products[i].oldPrice),stock:Number(req.body.stock??d.products[i].stock)};write(d);saveAudit('product_updated',{id:req.params.id});res.json(d.products[i])});
app.delete('/api/products/:id',admin,(req,res)=>{const d=read();d.products=d.products.filter(x=>x.id!==req.params.id);write(d);saveAudit('product_deleted',{id:req.params.id});res.json({ok:true})});
app.get('/api/dashboard',admin,(req,res)=>{const d=read(),paid=d.orders.filter(o=>o.status==='delivered'||o.status==='awaiting_service');res.json({salesToday:paid.filter(o=>o.createdAt.slice(0,10)===new Date().toISOString().slice(0,10)).reduce((s,o)=>s+o.amount,0),orders:d.orders.length,pending:d.orders.filter(o=>o.status==='awaiting_review').length,customers:d.customers.length,services:d.services.filter(s=>s.status==='available').length,tickets:d.tickets.filter(t=>t.status!=='closed').length,products:d.products.length});});
app.get('/api/orders',admin,(req,res)=>res.json(read().orders));
app.post('/api/orders',upload.single('receipt'),(req,res)=>{const d=read(),p=d.products.find(x=>x.id===req.body.productId&&x.active);if(!p)return res.status(400).json({error:'محصول یافت نشد'});const order={id:'SW-'+Date.now().toString().slice(-8),productId:p.id,product:p.name,customerName:req.body.customerName||'مشتری',telegram:req.body.telegram||'',phone:req.body.phone||'',amount:p.price,receipt:req.file?'/uploads/'+path.basename(req.file.path):'',status:'awaiting_review',createdAt:new Date().toISOString(),delivery:null};d.orders.unshift(order);d.customers.push({id:id(),name:order.customerName,telegram:order.telegram,phone:order.phone,createdAt:order.createdAt});d.notifications.unshift({id:id(),type:'order',title:'سفارش جدید',text:`${order.id} • ${order.product}`,at:order.createdAt,read:false});write(d);res.json({ok:true,orderId:order.id})});
app.use('/uploads',express.static(UPLOAD));
app.put('/api/orders/:id/status',admin,(req,res)=>{const d=read(),o=d.orders.find(x=>x.id===req.params.id);if(!o)return res.sendStatus(404);o.status=req.body.status;o.note=req.body.note||o.note||'';write(d);saveAudit('order_status',{id:o.id,status:o.status});res.json(o)});
app.put('/api/orders/:id/delivery',upload.fields([{name:'conf',maxCount:1},{name:'qr',maxCount:1}]),admin,(req,res)=>{const d=read(),o=d.orders.find(x=>x.id===req.params.id);if(!o)return res.sendStatus(404);o.delivery={subscription:req.body.subscription||'',notes:req.body.notes||'',conf:req.files?.conf?.[0]?'/uploads/'+path.basename(req.files.conf[0].path):'',qr:req.files?.qr?.[0]?'/uploads/'+path.basename(req.files.qr[0].path):'',deliveredAt:new Date().toISOString()};o.status='delivered';d.services.unshift({id:id(),orderId:o.id,product:o.product,status:'assigned',subscription:o.delivery.subscription,conf:o.delivery.conf,qr:o.delivery.qr,assignedAt:o.delivery.deliveredAt});write(d);saveAudit('service_delivered',{orderId:o.id});res.json(o)});
app.get('/api/customers',admin,(req,res)=>res.json(read().customers));app.get('/api/tickets',admin,(req,res)=>res.json(read().tickets));app.get('/api/services',admin,(req,res)=>res.json(read().services));app.get('/api/notifications',admin,(req,res)=>res.json(read().notifications));app.get('/api/audit',admin,(req,res)=>res.json(read().audit));
app.get('/api/settings',admin,(req,res)=>res.json(read().settings));app.put('/api/settings',admin,(req,res)=>{const d=read();d.settings={...d.settings,...req.body};write(d);saveAudit('settings_updated');res.json(d.settings)});
app.get('/admin',(q,r)=>r.sendFile(path.join(ROOT,'admin.html')));
app.listen(PORT,HOST,()=>console.log(`Sami WireGuard store: http://${HOST}:${PORT}`));
